'use strict';
var assert = require('assert');
var fs = require('fs');
var vm = require('vm');
var path = require('path');
var target = process.env.STACKLINE_TEST_PACKAGE || path.resolve(__dirname, '..');
var source = fs.readFileSync(path.join(target,'setImmediate.js'),'utf8');
var seen = [];
var context = {setTimeout:setTimeout,clearTimeout:clearTimeout};
vm.runInNewContext(source,context);
assert.strictEqual(typeof context.setImmediate,'function');
assert.strictEqual(typeof context.clearImmediate,'function');
context.setImmediate(function(a,b){seen.push(a+b);},2,3);
context.clearImmediate(context.setImmediate(function(){seen.push('cancelled');}));
assert.deepEqual(seen,[]);
setTimeout(function(){assert.deepEqual(seen,[5]);console.log('Installed shim VM: asynchronous scheduling, arguments and cancellation passed.');},100);
var native=function(){};
var existing={setImmediate:native};
vm.runInNewContext(source,existing);
assert.strictEqual(existing.setImmediate,native);
